/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
export default function FiltersSection() {
  return (
    <section className="filters">
      <div data-v-24d04b9c="" className="store-wall-filters__content">
        <div
          data-v-635bf2e0=""
          data-v-24d04b9c=""
          className="filters-section store-wall-filters__content--only-desktop"
        >
          <h3
            data-v-635bf2e0=""
            data-test-id="filters-section-title"
            className="filters-section__title"
          >
            Ordenar por
          </h3>
          <nav
            data-v-635bf2e0=""
            data-test-id="filters-section-options"
            className="filters-section__options"
          >
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/?sortingId=2&sort=cerca-de-mi"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob filter-option__blob--secondary"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/sorting/near_me_light"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Cerca de mí
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/?sortingId=3&sort=mejor-valorados"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob filter-option__blob--secondary"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/sorting/rating_light"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Mejor valorados
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/?sortingId=4&sort=precio-de-entrega"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob filter-option__blob--secondary"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/sorting/delivery_fee_light"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Precio de entrega
                </h2>
              </a>
            </div>
          </nav>
        </div>
        <div
          data-v-635bf2e0=""
          data-v-24d04b9c=""
          className="filters-section store-wall-filters__content--only-desktop"
        >
          <h3
            data-v-635bf2e0=""
            data-test-id="filters-section-title"
            className="filters-section__title"
          >
            Tus filtros favoritos
          </h3>
          <nav
            data-v-635bf2e0=""
            data-test-id="filters-section-options"
            className="filters-section__options"
          >
            {/**/}
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/americana_34835/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/m91ga7z3haf0ghqvipk4"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Americana
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/hamburguesas_34789/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/inwbt21iyiizggz1alhk"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Hamburguesas
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/snacks_34750/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/r5koryzkjme5ouxddp2c"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Snacks
                </h2>
              </a>
            </div>
          </nav>
        </div>
        <div
          data-v-635bf2e0=""
          data-v-24d04b9c=""
          className="filters-section store-wall-filters__content--only-desktop"
        >
          <h3
            data-v-635bf2e0=""
            data-test-id="filters-section-title"
            className="filters-section__title"
          >
            Más filtros
          </h3>
          <nav
            data-v-635bf2e0=""
            data-test-id="filters-section-options"
            className="filters-section__options"
          >
            {/**/}
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/arabe_34690/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/so1z4pmoh8xjnnn7mvcx"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Árabe
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/asiatica_34834/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/zlxnvq0nujobiq2fpjb5"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Asiática
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/bocadillos_34819/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/zuurobratonms7fd5cbn"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Bocadillos
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/brunch_35670/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/vqtyl5rx1iscsii8sl6o"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Brunch
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/china_34810/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/ye1bfswfbpzdjwrv9mvd"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  China
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/churros_35671/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/bikaamyuxhiyimo43ae4"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Churros
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/comida-casera_35672/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/gv094nglfxplpeblcar0"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Comida casera
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/comida-local_35381/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/tvhfoysp3bp6xfgxpsn6"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Comida local
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/desayuno_35073/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/ttgdadieadpdsk6t9ach"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Desayuno
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/dulces_34802/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/hzgg3vnmaffyt9d0fkhx"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Dulces
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/espanola_35663/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/i0azbzlpse0dtq1zxvbk"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Española
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/gourmet_35076/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/k555kpe5vjh9yc8kdncr"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Gourmet
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/griega_35110/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/jqbnv1e8rgkvbllthwig"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Griega
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/grill_34811/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/dsu6knoymqxjgsvycjlv"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Grill
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/helado_34747/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/sc3e8ionxdhbqf3r7zfz"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Helado
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/india_34692/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/lnxmdsrf2xw5u5qrahpv"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  India
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/internacional_34694/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/mtlzvyu0q834e3nucpyg"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Internacional
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/italiana_34685/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/mos7cdyqo7wic3jcqsbu"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Italiana
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/japonesa_34791/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/jfnneic8qfdfhcsr9pjp"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Japonesa
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/kebab_34699/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/re6cgtlhjcrnqnma8put"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Kebab
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/latinoamericana_34691/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/lwc3zb4ucpdbosl6gzwz"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Latinoamericana
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/marisco_34820/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/jwdvk8qh8gyrn6aavkl4"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Marisco
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/mediterranea_34693/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/zbkfokveyv3ldwqejzp9"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Mediterránea
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/mexicana_34687/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/xc03fwfottdfeahuffqw"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Mexicana
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/milanesa_34715/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/w4yc0tyukig0ec588h69"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Milanesa
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/paella_35678/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/mfkauhuhb9jesstlinxf"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Paella
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/peruana_35673/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/ddauzxk6izh84v7moa8a"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Peruana
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/pescaderia_35373/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/ac6lwwdnizpce98di2gq"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Pescadería
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/pizza_34701/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/rwr4tfqs1uxtatfuguvb"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Pizza
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/poke_34767/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/xz8hwiqmpmixqgae5xai"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Poke
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/pollo_34809/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/i8abjcvwjxylemfkkznj"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Pollo
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/saludable_34697/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/u6ftskcwobyfmkq41esf"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Saludable
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/sin-gluten_34794/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/hqjq2gdzwegbjfhuchb1"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Sin gluten
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/supermercado_35369/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/h92rfhojd717cud9nbum"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Supermercado
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/sushi_34702/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/x3en7tdjtrhbpaxaolcw"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Sushi
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/tailandesa_34762/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/m6urjeiye5nwxfzjapsk"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Tailandesa
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/vegana_35674/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/adjeaobxnkjjuroijyil"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Vegana
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/vegetariana_34795/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/reeze0aztdnh4mzuzagw"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Vegetariana
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/venezolana_35675/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/ct6izfwmwd49li0gdpvo"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Venezolana
                </h2>
              </a>
            </div>
          </nav>
        </div>
        <div
          data-v-635bf2e0=""
          data-v-24d04b9c=""
          className="filters-section store-wall-filters__content--only-mobile"
        >
          <h3
            data-v-635bf2e0=""
            data-test-id="filters-section-title"
            className="filters-section__title"
          />
          <nav
            data-v-635bf2e0=""
            data-test-id="filters-section-options"
            className="filters-section__options"
          >
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option-mobile"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/#filter"
                className="filter-option"
                data-test-id="store-wall-filters-all-button"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/filterImage"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Filtros ›
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/americana_34835/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/m91ga7z3haf0ghqvipk4"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Americana
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/hamburguesas_34789/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/inwbt21iyiizggz1alhk"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Hamburguesas
                </h2>
              </a>
            </div>
            <div
              data-v-635bf2e0=""
              data-test-id="filters-section-option"
              className="filters-section__option"
            >
              <a
                data-v-78a4f09e=""
                data-v-635bf2e0=""
                href="/es/es/barcelona/restaurantes_1/snacks_34750/"
                className="filter-option"
                data-test-id="filter-option-link"
              >
                <div
                  data-v-78a4f09e=""
                  data-test-id="filter-option-blob"
                  className="filter-option__blob"
                >
                  <img
                    data-v-78a4f09e=""
                    src="https://res.cloudinary.com/glovoapp/q_30,c_pad,f_auto,dpr_1.0,h_22,w_22,b_transparent/filters/r5koryzkjme5ouxddp2c"
                    sizes="(min-width: 600px) 22px, 30px"
                    role="presentation"
                    data-test-id="filter-option-image"
                    width={22}
                    height={22}
                    loading="lazy"
                    className="filter-option__icon"
                  />
                </div>
                <h2
                  data-v-78a4f09e=""
                  data-test-id="filter-option-label"
                  className="filter-option__label"
                >
                  Snacks
                </h2>
              </a>
            </div>
          </nav>
        </div>
      </div>
    </section>
  );
}
